name: PR Debug
on:
 pull_request:
   types: [opened, synchronize, reopened, edited]
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: node -p "require(process.env.GITHUB_EVENT_PATH)"
